[package]
name = "shvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libludi={path="../libludi/"}
# melior = "0.18.5"
