[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
ambassador = "0.4.1"
derive_more = {version = "1.0.0", features = ["display"]}
itertools = "0.13.0"
libludi = {path = "../libludi/"}
num = "0.4.3"
rustyline = "14.0.0"
